
project_id = 'zqgyndjnnphgxjygoxcp'

[api]
enabled = true
port = 54321
schemas = ['public', 'storage', 'graphql_public']

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
no_api_key = false

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = '50MiB'

[auth]
enabled = true
port = 9999
site_url = 'https://dirigovotes.com'
additional_redirect_urls = ['http://localhost:5173', 'https://localhost:5173', 'https://30a5fb21-b349-4719-af2d-aeab12a8a859.lovableproject.com', 'http://dirigovotes.com', 'https://dirigovotes.com']
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

# Use subdomain email settings
email_template_custom_from_name = 'Dirigo Votes'
email_template_custom_from_email = 'no-reply@contact.dirigovotes.com'
email_from_name = 'Dirigo Votes'
email_from_address = 'no-reply@contact.dirigovotes.com'
email_template_system_from_name = 'Dirigo Votes'
email_template_system_from_email = 'no-reply@contact.dirigovotes.com'

# Increase email rate limiting further
rate_limit_email_sent = 50
email_confirm_change_email_template_id = 'd-7e4e79720a064eeeb2each'
disable_confirm_change_email = false

[realtime]
enabled = true

[edge_functions]
[edge_functions.send-report]
verify_jwt = true
[edge_functions.send-position-report]
verify_jwt = true
[edge_functions.send-email]
verify_jwt = true
