
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
port = 54325

[storage]
port = 54326

[realtime]
port = 54327

[functions]
[functions.check-vote-tracking]
[functions.create-vote-tracking]
[functions.delete-vote-tracking]
