
project_id = "zqgyndjnnphgxjygoxcp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true

[edge_functions]
enabled = true

[[edge_functions.routes]]
path = "/check-vote-tracking"
function = "check-vote-tracking"

[[edge_functions.routes]]
path = "/delete-vote-tracking"
function = "delete-vote-tracking"
